[package]
name = "string-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
regex = "1.5.4"
colored = "2.0.0"
term-table = "1.3.2"
figlet-rs = "0.1.3"